name: example
description: Simple, single-class example exercising sudoku_api.
version: 1.2.2
homepage: https://github.com/AlvinRamoutar/sudoku-api

environment:
  sdk: ">=2.1.2 <3.0.0"

dependencies:
  sudoku_api: ^1.2.2

dev_dependencies:
  test: ^1.17.5
