name: sudoku_api
description: sudoku_api simplifies the generation, interaction, and management of Sudoku Puzzles.
version: 1.1.0
homepage: https://github.com/AlvinRamoutar/sudoku-api

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.0.4
  tuple: ^1.0.3
  collection: ^1.14.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
